#!/bin/bash
#***********************************************  #KickPi-OS install script  ***********************************
# Install KickPi-OS
# B.Titze 2021
# https://libraries.io/github/botolo78/RetroPie-Manager
# Alternative: https://github.com/daeks-archive/yarman

#Romolus Search Roms :-)  https://github.com/ArthurMoore85/romulus



sudo apt-get install virtualenv python-dev
cd
cd
git clone https://github.com/botolo78/RetroPie-Manager.git
cd RetroPie-Manager
make install


# Autostart add /home/pi/RetroPie-Manager/bin/python /home/pi/RetroPie-Manager/manage.py runserver 0.0.0.0:8000 --settings=project.settings_production --noreload > /dev/null 2>&1 
# to sudo nano /opt/retropie/configs/all/autostart.sh


Update
sudo kill -9 $(pgrep -f RetroPie-Manager)
cd 
cd Retropie-Manager
make clean
git reset --hard HEAD
git pull
make install
Reinstall
sudo kill -9 $(pgrep -f RetroPie-Manager)
cd 
rm -rf Retropie-Manager
git clone https://github.com/botolo78/RetroPie-Manager.git
cd RetroPie-Manager
make install
Stop RetroPie-Manager
sudo kill -9 $(pgrep -f RetroPie-Manager)
