#!/bin/bash
# Install KickPi-OS
# B.Titze 2021
# KickPi-OS updater
sudo raspi-config nonint do_expand_rootfs
LED
update.sh
sudo rm -rf ~/KickPi-OS
LED_off
sudo dpkg --configure -a
sudo apt -y --fix-broken install
sudo apt -f -y install

wget -q --spider http://google.com

 if [ $? -eq 0 ]; then



sudo rm -rf /home/$USER/KickPi-OS/
#sudo rm -rf /home/$USER/.KickPi-OS/


  
      cd
      git clone --depth=1 https://github.com/Jodels2002/KickPi-OS.git
      sudo chmod -R 777 KickPi-OS
      sudo cp -rf /home/$USER/KickPi-OS /home/$USER/.KickPi-OS    
      LED_off
      sudo cp -f -R /home/$USER/KickPi-OS/scripts/* /usr/local/bin
        sudo cp -f -R /home/$USER/KickPi-OS/scripts/.bashrc /usr/local/bin
      sudo chmod -R 777 /usr/local/bin
      /home/$USER/KickPi-OS/scripts/pikickme.sh
 else
    whiptail --msgbox " Sorry, you must first connect to internet :-)" 20 50 1
 fi



      


