#!/bin/bash
# Install KickPi-OS
# B.Titze 2021
# KickPi-OS updater
LED
sleep 1s
LED_off
sudo apt -y --fix-broken install
wget -q --spider http://google.com

if [ $? -eq 0 ]; then
sudo apt -y --fix-broken install
LED_front
sudo apt-get -y update
LED_off
sudo apt-get -y upgrade
LED_body
sudo rm -rf /home/$USER/KickPi-OS/
sudo rm -rf /home/$USER/.KickPi-OS/
else
    whiptail --msgbox " Sorry, you must first connect to internet :-)" 20 50 1
fi


if [ ! -f "/home/$USER/Amiga/conf/default.uae" ]; then

     clear
     toilet "KickPi-OS" --metal
       
    else
    
      clear
      toilet "KickPi-OS" --metal
      echo " "
      echo "Default config for Amiberry found...  "
      
fi
      cd
      sudo apt -y upgrade
      cd
      git clone --depth=1 https://github.com/Jodels2002/KickPi-OS.git
      sudo chmod -R 777 KickPi-OS
      /home/$USER/KickPi-OS/scripts/pikickme.sh


